# Vagrant.configure("2") do |config|
#     config.vm.box = "debian/bullseye64"

#     config.vm.provider "virtualbox" do |vb|
#         vb.memory = 1024
#         vb.cpus = 1
#     end

#     config.vm.provision "shell", inline: <<-SHELL
#         export DEBIAN_FRONTEND=noninteractive

#         apt-get update
#         apt-get install -y curl git zsh

#         su -l vagrant -s "/bin/sh" -c "curl -fsSO https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh; chmod 755 install.sh; ./install.sh --unattended"
#         sed -i 's/ZSH_THEME=".*"/ZSH_THEME="superjarin"/g' /home/vagrant/.zshrc
#         chsh -s /bin/zsh vagrant
#         echo "cd /vagrant" >> /home/vagrant/.zshrc
#     SHELL
# end

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bullseye64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end

    config.vm.provision "shell", path: "scripts/shared.sh"

    config.vm.define "axbrisseS" do |control|
        control.vm.hostname = "axbrisseS"
        control.vm.network "private_network", ip: "192.168.56.110"

        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "axbrisseS"]
        end

        control.vm.provision "shell", path: "scripts/server.sh"
    end

    config.vm.define "axbrisseSW" do |control|
        control.vm.hostname = "axbrisseSW"
        control.vm.network "private_network", ip: "192.168.56.111"

        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "axbrisseSW"]
        end

        control.vm.provision "shell", path: "scripts/server_worker.sh"
    end
end