PROVIDER = "virtualbox"

SERVER_IP = "192.168.56.110"
SERVER_NAME = "axbrisseS"

AGENT_IP = "192.168.56.111"
AGENT_NAME = "axbrisseSW"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"
  config.vm.provider PROVIDER do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define SERVER_NAME, primary: true do |control|
    control.vm.network "private_network", ip: SERVER_IP
    control.vm.synced_folder "./shared", "/shared"
    control.vm.hostname = SERVER_NAME
    control.vm.provider PROVIDER do |v|
      v.customize ["modifyvm", :id, "--name", SERVER_NAME]
    end
    control.vm.provision "shell", path: "scripts/server.sh", env: { "SERVER_IP" => SERVER_IP }
  end

  config.vm.define AGENT_NAME do |control|
    control.vm.network "private_network", ip: AGENT_IP
    control.vm.synced_folder "./shared", "/shared"
    control.vm.hostname = AGENT_NAME
    control.vm.provider PROVIDER do |v|
      v.customize ["modifyvm", :id, "--name", AGENT_NAME]
    end
    control.vm.provision "shell", path: "scripts/agent.sh", env: { "SERVER_IP" => SERVER_IP }
  end
end